In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size =10000

In [7]:
for words in sent:
    print(words)

the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am a good developer
understand the meaning of words
your videos are good


In [8]:
[one_hot(words,voc_size) for words in sent]

[[867, 9561, 4908, 2524],
 [867, 9561, 4908, 9769],
 [867, 8238, 4908, 5870],
 [1676, 5726, 6592, 9725, 7455],
 [1676, 5726, 6592, 9725, 2612],
 [434, 867, 9094, 4908, 1390],
 [378, 5393, 4591, 9725]]

In [9]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [14]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [15]:
embedded_docs

array([[   0,    0,    0,    0,  867, 9561, 4908, 2524],
       [   0,    0,    0,    0,  867, 9561, 4908, 9769],
       [   0,    0,    0,    0,  867, 8238, 4908, 5870],
       [   0,    0,    0, 1676, 5726, 6592, 9725, 7455],
       [   0,    0,    0, 1676, 5726, 6592, 9725, 2612],
       [   0,    0,    0,  434,  867, 9094, 4908, 1390],
       [   0,    0,    0,    0,  378, 5393, 4591, 9725]])

In [16]:
dim = 10

In [17]:
model = Sequential()

In [18]:
model.add(Embedding(voc_size,dim,input_length = sent_length))

In [19]:
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 146ms/step


array([[[-0.02710913,  0.02198478, -0.0420875 ,  0.03489082,
          0.04291829, -0.04566021, -0.02692273,  0.0314806 ,
         -0.04660039, -0.01355387],
        [-0.02710913,  0.02198478, -0.0420875 ,  0.03489082,
          0.04291829, -0.04566021, -0.02692273,  0.0314806 ,
         -0.04660039, -0.01355387],
        [-0.02710913,  0.02198478, -0.0420875 ,  0.03489082,
          0.04291829, -0.04566021, -0.02692273,  0.0314806 ,
         -0.04660039, -0.01355387],
        [-0.02710913,  0.02198478, -0.0420875 ,  0.03489082,
          0.04291829, -0.04566021, -0.02692273,  0.0314806 ,
         -0.04660039, -0.01355387],
        [ 0.02228068, -0.01846739,  0.02302668, -0.00866429,
          0.04609736,  0.0042066 , -0.00523771,  0.0212944 ,
          0.03339234, -0.02380816],
        [ 0.03969106,  0.03223139,  0.02366641,  0.00451189,
          0.04830524,  0.00716377,  0.00892558, -0.0156117 ,
         -0.00489325,  0.04110351],
        [-0.02971259,  0.01125639, -0.04055054,  0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0,  867, 9561, 4908, 2524])

In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 34ms/step


array([[-0.02710913,  0.02198478, -0.0420875 ,  0.03489082,  0.04291829,
        -0.04566021, -0.02692273,  0.0314806 , -0.04660039, -0.01355387],
       [-0.02710913,  0.02198478, -0.0420875 ,  0.03489082,  0.04291829,
        -0.04566021, -0.02692273,  0.0314806 , -0.04660039, -0.01355387],
       [-0.02710913,  0.02198478, -0.0420875 ,  0.03489082,  0.04291829,
        -0.04566021, -0.02692273,  0.0314806 , -0.04660039, -0.01355387],
       [-0.02710913,  0.02198478, -0.0420875 ,  0.03489082,  0.04291829,
        -0.04566021, -0.02692273,  0.0314806 , -0.04660039, -0.01355387],
       [ 0.02228068, -0.01846739,  0.02302668, -0.00866429,  0.04609736,
         0.0042066 , -0.00523771,  0.0212944 ,  0.03339234, -0.02380816],
       [ 0.03969106,  0.03223139,  0.02366641,  0.00451189,  0.04830524,
         0.00716377,  0.00892558, -0.0156117 , -0.00489325,  0.04110351],
       [-0.02971259,  0.01125639, -0.04055054,  0.04372182,  0.02076546,
         0.04654649,  0.02624107,  0.03821584